// Generate app + tray icons by rasterizing an inline SVG through Electron's
// canvas, then pack a multi-size .ico by hand. No native image deps.
// Run with: electron scripts/gen-icons.cjs
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const resDir = path.join(root, 'build-resources');
fs.mkdirSync(resDir, { recursive: true });

// The faceboard mark: dark rounded square + light face with an accent smile.
const svg = (s) => `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 100 100">
  <rect x="5" y="5" width="90" height="90" rx="22" fill="#111114" stroke="#2c2c33" stroke-width="2"/>
  <circle cx="50" cy="48" r="27" fill="none" stroke="#ededf0" stroke-width="5"/>
  <circle cx="40" cy="43" r="3.8" fill="#ededf0"/>
  <circle cx="60" cy="43" r="3.8" fill="#ededf0"/>
  <path d="M39 57c3.5 4.5 7 6.5 11 6.5s7.5-2 11-6.5" fill="none" stroke="#7cc7ff" stroke-width="5.5" stroke-linecap="round"/>
</svg>`;

async function renderPng(win, size) {
	const markup = svg(size);
	const html =
		'<!doctype html><meta charset="utf-8"><body style="margin:0;background:transparent">' +
		`<canvas id="c" width="${size}" height="${size}"></canvas><script>` +
		'window.__png = new Promise((resolve) => {' +
		'const img = new Image();' +
		'img.onload = () => { const c = document.getElementById("c"); const ctx = c.getContext("2d");' +
		`ctx.clearRect(0,0,${size},${size}); ctx.drawImage(img,0,0,${size},${size}); resolve(c.toDataURL("image/png")); };` +
		'img.src = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(' +
		JSON.stringify(markup) +
		')));});</script></body>';
	await win.loadURL('data:text/html;base64,' + Buffer.from(html).toString('base64'));
	const dataUrl = await win.webContents.executeJavaScript('window.__png');
	return Buffer.from(dataUrl.split(',')[1], 'base64');
}

// Minimal ICO container that embeds PNG images (supported by modern Windows).
function packIco(entries) {
	const count = entries.length;
	const header = Buffer.alloc(6 + count * 16);
	header.writeUInt16LE(0, 0);
	header.writeUInt16LE(1, 2);
	header.writeUInt16LE(count, 4);
	let offset = header.length;
	const dirs = [];
	entries.forEach((e, i) => {
		const o = 6 + i * 16;
		header.writeUInt8(e.size >= 256 ? 0 : e.size, o);
		header.writeUInt8(e.size >= 256 ? 0 : e.size, o + 1);
		header.writeUInt8(0, o + 2);
		header.writeUInt8(0, o + 3);
		header.writeUInt16LE(1, o + 4);
		header.writeUInt16LE(32, o + 6);
		header.writeUInt32LE(e.data.length, o + 8);
		header.writeUInt32LE(offset, o + 12);
		offset += e.data.length;
		dirs.push(e.data);
	});
	return Buffer.concat([header, ...dirs]);
}

app.whenReady().then(async () => {
	const win = new BrowserWindow({ show: false, width: 600, height: 600 });
	const sizes = [16, 24, 32, 48, 64, 128, 256, 512];
	const pngs = {};
	for (const s of sizes) pngs[s] = await renderPng(win, s);

	// electron-builder icons
	fs.writeFileSync(path.join(resDir, 'icon.png'), pngs[512]);
	fs.writeFileSync(
		path.join(resDir, 'icon.ico'),
		packIco([16, 24, 32, 48, 64, 128, 256].map((s) => ({ size: s, data: pngs[s] })))
	);

	// tray icon embedded as a data URL so it needs no runtime file
	const trayB64 = pngs[32].toString('base64');
	fs.writeFileSync(
		path.join(root, 'electron', 'tray-icon.ts'),
		'// Generated by scripts/gen-icons.cjs — do not edit by hand.\n' +
			`export const TRAY_ICON_DATA_URL = 'data:image/png;base64,${trayB64}';\n`
	);

	// static favicon for the phone page / browser tab
	fs.writeFileSync(path.join(root, 'static', 'favicon.png'), pngs[64]);

	console.log('GEN_ICONS_OK', Object.keys(pngs).map((s) => `${s}:${pngs[s].length}`).join(' '));
	app.quit();
	process.exit(0);
});
